# Generated by Django 5.2.9 on 2026-01-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='raw_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
